### ISSUE TITLE
Measure nomodeset boot parameter

### ISSUE THREAD

**Issue by mcphail** [ubuntu/ubuntu-report#20]
It would be interesting to know how many users are having to run the installer with `nomodeset` as a boot parameter. I'd had to do this for several iterations of the installer, lest I be faced with a black screen. Thankfully, for me,18.04 did not require this.

I feel this would be a useful metric. The quality objective should be for no users to have to pass `nomodeset` to complete the installation. What do you think?

**Comment by didrocks** [comment]
I'm unsure, I would tend to say no and those should be dealt via bug reports (because having the metrics without associated bugs and configurations doesn't hel us to fix the issues).

We can see that for a lot of "workarounds" settings, and where would we draw the line? That's why I'm tempted to think this is a good idea in theory, but adding this metrics wouldn't help solve the underlying problem. Thanks for your suggestion though!
