### ISSUE TITLE
CPU Reporting Broken

### ISSUE THREAD

**Issue by hk21702** [ubuntu/ubuntu-report#68]
CPU reporting seems to be broken on both the main branch and add_collector_service. This is happening in both Desktop 24.04 and WSL 24.04.

From what I can tell, it is an issue with parsing the output of `lscpu -J`.

Currently, the filter being used goes uses the io reader to go line by line, trying to match each line with the regex. However, this means it never matches the regex which is looking for something along the lines of `{"field": "<key>", "data": "<value>"}`, however in the output, these will be split up into different lines. (This regex seems too strict anyways, and even if everything were on one line, would fail to capture cases where there is info after the data field such as `"data": "<value>", "children": [...` such as for CPU(s).

![image](https://github.com/user-attachments/assets/3e0ca862-061d-4260-b3f9-5358817b215c)

To fix this, since we need the field and data paired together, it may be easier to instead of using the Json format, just scan line by line from the human-readable response, trim the line, split at `: ` and try to match the left with a known key via a switch.

![image](https://github.com/user-attachments/assets/1018b6cb-4351-4de4-9c6b-71f92e63a5be)

Alternatively, do a proper parsing of the json return

**Comment by didrocks** [comment]
You are correct! CPU is not reported at all anymore (tested locally too).

 As you mention, this is probably due to a too restrictive regexp. I’m hesitant about going to the human readable format though for parsing. I always prefer relying on the machine output. That way:
- you know that you won’t have accidental errors reported to stdout when they should be in stderr or any other warnings breaking your parsing
- even if we launch with LANG=C, some softwares don’t comply with that and you end up with localized content.

My suggestion would still to go on with parsing the json output. There are 2 fixing it:
- as we will probably not rely on ubuntu-report in the future (by next LTS) to report ubuntu telemetry, we can just go with a fix. Meaning:
  1. Adding a test reproducing the issue
  2. Fixing the regexp
  3. SRUing the fixes
- or (more involved), loading the full json and parsing it as json (which I should have done from the beginning in all honesty), and use the declared fields

With the current future plan for telemetry, I would really go with the first proposal. Tell me what's your thoughts about this!
